  
name: Docker CD

on:
  push:
    branches: 
      - gh-actions
  pull_request:
    branches: 
      - gh-actions

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Docker login
      env:
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker build
      run: |
       docker build . -t openlxp/openlxp-xds-ui
    - name: Push Image
      run: |
        docker push openlxp/openlxp-xds-ui
